### ISSUE TITLE
Versión del CMS se tiene instalado y sus módulos instalados

### ISSUE THREAD

**Issue by macagua** [TLIPEA/Web_Oficial#1]
Hola @chudacontreras 

¿Qué versión del CMS se tiene instalado y sus módulos?

Para replicar la instalación y hacer pruebas

**Comment by chudacontreras** [comment]
es joomla 2.5.19 los modulos son los que trae la plantilla por defecto mas
akeeba y admintools

## 

Jesús Contreras (Chuda).
Teléfono: +58-412-0169757
Usuario Linux  #485423
IBM ACE Professional Certificate.
http://chuda.org.ve http://www.chuda.org.ve
_Happy Hacking!_

**Comment by macagua** [comment]
@chudacontreras puedes pasar las URL del tema y del admintools para descargarlas ?

**Comment by macagua** [comment]
@chudacontreras y @styp152 cual es la plantilla y cual versión están usando para el sitio?

**Comment by styp152** [comment]
En la rama install del repo esta para montar el sitio que esta respaldado con akeeba, falta colocar un  usuario genérico para el admin

**Comment by hellfish2** [comment]
@chudacontreras @styp152 pueden subir los archivos originales de la pagina web de la comunidad para poder organizarlo compañeros?

**Comment by chudacontreras** [comment]
joomla 2.5 pero tenemos que migrarla a joomla 3 por eso estoy esperando a
que el dominio este activo para migrar ;-)

## 

Jesús Contreras (Chuda).
Teléfono: +58-412-0169757
Usuario Linux  #485423
IBM ACE Professional Certificate.
http://chuda.org.ve http://www.chuda.org.ve
_Happy Hacking!_

**Comment by hellfish2** [comment]
puedes pasarme lo que esta la BD y los archivos y lo que hacemos es que cuando el dominio este activo creamos otra rama @chudacontreras

**Comment by gerfig** [comment]
+1 hay que irse a joomla 3

**Comment by hellfish2** [comment]
asi es @lestat00 +1

**Comment by chudacontreras** [comment]
carlos todo esta en el repo es un istalador de akebba, es un respaldo viejo
de la pagina de cuando se subio por primera vez

## 

Jesús Contreras (Chuda).
Teléfono: +58-412-0169757
Usuario Linux  #485423
IBM ACE Professional Certificate.
http://chuda.org.ve http://www.chuda.org.ve
_Happy Hacking!_

2015-02-11 22:47 GMT-04:30 Carlos Malave notifications@github.com:

**Comment by hellfish2** [comment]
@chudacontreras Compa puedes hacer un tag a el commit donde dices que esta porque revisando no lo veo lo unico que veo es unos commits con unos readme de @styp152 y disculpa man

**Comment by chudacontreras** [comment]
en el repo existen dos ramas una es la master y otra la install

<joke> eso pasa por trabajar con gente que no es del área</joke>

## 

Jesús Contreras (Chuda).
Teléfono: +58-412-0169757
Usuario Linux  #485423
IBM ACE Professional Certificate.
http://chuda.org.ve http://www.chuda.org.ve
_Happy Hacking!_

**Comment by hellfish2** [comment]
LOL jajajajjaja no lo pille mala mia bro.... @chudacontreras
